### ISSUE TITLE
xts series data

### ISSUE THREAD

**Issue by robschick** [larryzheng0/Data-Package#2]
Hi Both - can you add two columns back into the xts series data? We need the deployID for filtering in the shiny app, and the date_time object for plotting within dygraph.

**Comment by larryzheng0** [comment]
Hi Dr. Schick, looks like "an xts object is essentially a matrix which has been indexed by dates", so it's not going to have a date_time column, and you can't have non-numeric columns like deployID.

**Comment by robschick** [comment]
Thanks Larry. Let me take a look at my one off version on my desktop. I wonder if we'll need a list structure, then, where each named element has the xts object for each whale. We need this so that the shiny app can update with the correct animal's dive profile when a user selects and individual
